version: '3'

services:
  visualization:
    build:
      context: ./app/visualization
    ports:
      - "5000:5000"
    depends_on:
      - data-generator
    volumes:
      - ./static:/app/static

  data-generator:
    build:
      context: ./app/data-generator
    depends_on:
      - redis
    volumes:
      - ./static:/app/static

  redis:
    image: "redis:latest"
